FROM golang:alpine as builder

RUN apk update && apk upgrade && apk add --no-cache bash git openssh

COPY /calendar /go/src/calendar
WORKDIR /go/src/calendar/cmd/notificator

ENV GO111MODULE=on
RUN go mod download
RUN go build -v .
FROM alpine
RUN adduser -S -h /app notificator_user
COPY --from=builder /go/src/calendar /app/
WORKDIR /app/cmd/notificator
USER notificator_user
CMD ["./notificator"]