API:
  Port: 50051
  Logger:
    level: info
    encoding: console
    outputPaths:
      - stdout
    errorOutputPaths:
      - stderr
  DB:
    user: api_user
    password: 123456
    dbname: Calendar
    host: psql
  Rabbit:
    user: api_user
    password: 123456
    host: rabbit
    port: 5672
    vhost: my_vhost